name: test-k8s-files

on:
  [push]

jobs:
  test-k8s-files:
    name: 'k8s'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - uses: balchua/microk8s-actions@v0.3.0
        with:
          channel: '1.25/stable'
      - name: Test MicroK8s
        id: k8s
        run: |
          helm template . -f ~/Downloads/values.yaml
          kubectl apply -f sources/student_service.yaml
          kubectl apply -f sources/mongodb.yaml
          sleep 5 
          kubectl get pods -A -o wide